#include <gtest/gtest.h>
#include <pcapplusplus/PcapFileDevice.h>
#include <pcapplusplus/Packet.h>
#include <pcapplusplus/DnsLayer.h>
#include <pcapplusplus/IPv4Layer.h>
#include "DnsAnalyzer.h"

using namespace std;
Binary makeBinaryFromRaw(const pcpp::RawPacket& raw) {
    Binary bin;
    bin.length = raw.getRawDataLen();
    bin.data = new uint8_t[bin.length];
    std::memcpy(bin.data, raw.getRawData(), bin.length);
    return bin;
}

// sample dns packet generated by chatgpt
static Binary makeTestDnsPacket() {
    static uint8_t packet[] = {
        // Ethernet (14 bytes)
        0xff,0xff,0xff,0xff,0xff,0xff, // dst MAC
        0x00,0x11,0x22,0x33,0x44,0x55, // src MAC
        0x08,0x00,                     // EtherType = IPv4

        // IPv4 (20 bytes)
        0x45,0x00,0x00,0x1c,0x00,0x00,0x40,0x00,0x40,0x11,0x00,0x00,
        192,168,0,1, // src IP
        192,168,0,2, // dst IP

        // UDP (8 bytes)
        0x00,0x35,0x00,0x35,0x00,0x08,0x00,0x00,

        // DNS (12 bytes)
        0xab,0xcd,   // Transaction ID = 0xabcd
        0x81,0x80,   // Flags: qr=1 (response), rcode=0 (success)
        0x00,0x01,   // QDCOUNT
        0x00,0x01,   // ANCOUNT
        0x00,0x00,   // NSCOUNT
        0x00,0x00    // ARCOUNT
    };
    return Binary{packet, sizeof(packet)};
}

TEST(DnsReporterTest, ExtractDnsPayload) {
    Binary bin = makeTestDnsPacket();
    Binary dnsPayload = DnsReporter::extractDnsPayload(bin);

    ASSERT_EQ(dnsPayload.length, bin.length - 14 - 20 - 8); // total - eth - ipv4 - udp
    EXPECT_EQ(dnsPayload.data[0], 0xab); // first byte of transaction ID
    EXPECT_EQ(dnsPayload.data[1], 0xcd); // second byte of transaction ID
}

TEST(DnsReporterTest, TransactionID) {
    Binary bin = makeTestDnsPacket();
    uint16_t txid = DnsReporter::transactionID(bin);
    EXPECT_EQ(txid, 0xabcd);
}

TEST(DnsReporterTest, IsResponse) {
    Binary bin = makeTestDnsPacket();
    bool qr = DnsReporter::isResponse(bin);
    EXPECT_TRUE(qr); // because flags 0x81, 0x80 => qr=1
}

TEST(DnsReporterTest, IsSuccessResponse) {
    Binary bin = makeTestDnsPacket();
    bool success = DnsReporter::isSuccessResponse(bin);
    EXPECT_TRUE(success); // rcode=0
}

TEST(DnsReporterTest, GetInitialReport){
    DnsReporter reporter;
    EXPECT_EQ(0, reporter.getReport().recieved);
    EXPECT_EQ(0, reporter.getReport().success);
    EXPECT_EQ(0, reporter.getReport().failed);
    EXPECT_EQ(0, reporter.getReport().total);
}

TEST(DnsReporterTest, ValidPcapTransactionsFile) {
    Report rep;
    pcpp::IFileReaderDevice* reader = pcpp::IFileReaderDevice::getReader("../samples/capture.pcapng");
    if (!reader) {
        std::cerr << "Error: unsupported file type or cannot create reader\n";
    }

    if (!reader->open()) {
        std::cerr << "Error: could not open pcap file \n";
        delete reader;
    }

    DnsReporter reporter;
    pcpp::RawPacket rawPacket;
    int dnsCount = 0;

    while (reader->getNextPacket(rawPacket)) {
    //    cout << "count is " << dnsCount << endl;
        pcpp::Packet parsed(&rawPacket);
        auto* dns = parsed.getLayerOfType<pcpp::DnsLayer>();
        if (!dns) continue; // skip non-DNS

        Binary bin = makeBinaryFromRaw(rawPacket);
        reporter.addBinary(bin);
        dnsCount++;
        EXPECT_EQ(reporter.getReport().recieved, dnsCount);
        delete[] bin.data;
    }

    


    reader->close();
    delete reader;
    rep = reporter.getReport();
    EXPECT_EQ(rep.success, 22);
    EXPECT_EQ(rep.failed, 1);
    return;
}
